/*
-- Query: SELECT * FROM VENDITA_BIGLIETTI.cliente
LIMIT 0, 50000

-- Date: 2025-04-02 11:51
*/
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (1,'Brescia','Antonio','mail1@gmail.com','333445566','S',200,'2024-01-01','2028-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (2,'Cliente Prova','Mio','mail2@gmail.com','333445577','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (3,'Buffo','Nicola','mail3@libero.it','333556677','S',150,'2020-10-26','2026-10-25');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (4,'Cliente 4','Nome 4','mail4@gmail.com','333123454','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (5,'Cliente 5','Nome 5','mail5@gmail.com','333123455','S',265,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (6,'Cliente 6','Nome 6','mail6@gmail.com','333123456','S',266,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (7,'Cliente 7','Nome 7','mail7@gmail.com','333123457','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (8,'Cliente 8','Nome 8','mail8@gmail.com','333123458','S',268,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (9,'Cliente 9','Nome 9','mail9@gmail.com','333123459','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (10,'Cliente 10','Nome 10','mail10@gmail.com','3331234510','S',2610,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (11,'Cliente 11','Nome 11','mail11@gmail.com','3331234511','S',2611,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (12,'Cliente 12','Nome 12','mail12@gmail.com','3331234512','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (13,'Cliente 13','Nome 13','mail13@gmail.com','3331234513','S',2613,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (14,'Cliente 14','Nome 14','mail14@gmail.com','3331234514','S',2614,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (15,'Cliente 15','Nome 15','mail15@gmail.com','3331234515','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (16,'Cliente 16','Nome 16','mail16@gmail.com','3331234516','S',2616,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (17,'Cliente 17','Nome 17','mail17@gmail.com','3331234517','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (18,'Cliente 18','Nome 18','mail18@gmail.com','3331234518','S',2618,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (19,'Cliente 19','Nome 19','mail19@gmail.com','3331234519','N',NULL,NULL,NULL);
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (20,'Cliente 20','Nome 20','mail20@gmail.com','3331234520','S',2620,'2022-01-01','2027-12-31');
INSERT INTO cliente (`cod_cliente`,`cognome_cliente`,`nome_cliente`,`mail_cliente`,`num_tel_cliente`,`iscrizione_programma_defelta`,`punti_cliente`,`data_iscrizione_cliente`,`scadenza_iscrizione_cliente`) VALUES (21,'Cliente 21','Nome 21','mail21@gmail.com','3331234521','N',NULL,NULL,NULL);


COMMIT;